<!-- Edit afbeelding -->
<div class="modal fade" id="editImage" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content bg-dark">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit afbeelding</h5>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <input type="hidden" name="imageId" value="" />
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label" for="nameImage">Afbeelding naam</label>
                                <input name="editNameImage" class="form-control" placeholder="Afbeelding naam" type="text" value="">
                            </div>
                            <div class="form-group">
                                <label for="nameImage">Alt</label>
                                    <input name="editAlt" class="form-control" placeholder="Alt" type="text" value="">
                            </div>
                            <div class="form-group">
                                <label for="nameImage">Omschrijving</label>
                                <input name="editDdescriptionImage" class="form-control" placeholder="Omschrijving" type="text" value="">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button id="saveImageDetails" type="button" class="btn btn-secondary">Save</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>