<!-- Edit Image Modal -->
<div class="modal fade" id="editImageModal" tabindex="-1" aria-labelledby="editImageModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editImageModalLabel">Edit afbeelding</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <input type="hidden" name="imageId" value="" />
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label" for="nameImage">Afbeelding naam</label>
                                <input name="editNameImage" class="form-control" placeholder="Afbeelding naam" type="text" value="">
                            </div>
                            <div class="form-group">
                                <label for="nameImage">Alt</label>
                                <input name="editAlt" class="form-control" placeholder="Alt" type="text" value="">
                            </div>
                            <div class="form-group">
                                <label for="nameImage">Omschrijving</label>
                                <input name="editDdescriptionImage" class="form-control" placeholder="Omschrijving" type="text" value="">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button id="saveImageDetails" type="button" class="btn btn-primary">Save</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>