<!-- File Modal -->
<div class="modal fade" id="filesModal" tabindex="-1" aria-labelledby="filesModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="filesModalLabel">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row" style="margin-bottom:15px;" id="filesFrame">

                </div>
                <div class="row">
                    <div class="col-sm-12 col-md-12 col-lg-12">
                        <div class="form-group has-feedback">
                            <div class="input-group mb-2">
                                <div class="input-group-prepend input-group-addon">
                                    <label class="input-group-text  btn btn-primary btn-file">
                                        Browse&hellip; <input type="file" class="form-control" name="filelink">
                                    </label>
                                </div>
                                <input type="text" class="form-control" name="fileUploadFileName" readonly>
                            </div>
                        </div>
                    </div>
                </div>
                <button id="saveFiles" type="button" class="btn btn-default">Add</button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>