<!-- File's -->
<div class="row" style="margin-bottom:15px;" id="filesFrame">

</div>
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <div class="form-group has-feedback">
            <div class="input-group">
                <span class="input-group-addon"><span class="glyphicon glyphicon-link" aria-hidden="true"></span></span>
                <input type="text" class="form-control" name="youtubevideolink">
            </div>
        </div>
    </div>
</div>
<button id="saveYouTubeVideo" type="button" class="btn btn-default">Add</button>