<!-- Afbeeldingen -->
<div class="modal fade bd-example-modal-lg" id="imageModal" tabindex="-1" role="dialog" aria-labelledby="imageLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content bg-dark">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Files</h5>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row grid img-thumbnails" id="sortableItems">
                    <?php
                    if (count($images) > 0) {
                        foreach ($images AS $image) {
                            foreach ($image->getImageTypes('150x150') AS $imageType) {
                                ?>
                                <div class="col-md-4 tile">
                                    <div id="image<?php echo $image->getImageId(); ?>">
                                        <?php
                                        echo '<img class="img-thumbnail" src="/' . $imageType->getFolder() . $imageType->getFileName() . '?v=' . rand() . '" alt="' . $image->getAlt() . '"/>';
                                        ?>
                                        <div class="imageOptions">
                                            <span data-imageid="<?php echo $image->getImageId(); ?>"
                                                  class="btn btn-secondary btn-sm editImage" data-dismiss="modal"
                                                  data-target="#showImages"><i class="fas fa-edit"></i></span>
                                            <span data-imageid="<?php echo $image->getImageId(); ?>"
                                                  class="btn btn-secondary btn-sm deleteImageObject"><i
                                                        class="fas fa-trash"></i></span>
                                            <span data-id="<?php echo $returnURL['id'] ?>"
                                                  data-route="<?php echo $returnURL['route'] ?>"
                                                  data-action="<?php echo $returnURL['action'] ?>"
                                                  data-imageid="<?php echo $image->getImageId(); ?>"
                                                  class="btn btn-secondary btn-sm recropImage"><i class="fa fa-crop"
                                                                                                  aria-hidden="true"></i></span>
                                            <span data-id="<?php echo $returnURL['id'] ?>"
                                                  data-route="<?php echo $returnURL['route'] ?>"
                                                  data-action="<?php echo $returnURL['action'] ?>"
                                                  data-imageid="<?php echo $image->getImageId(); ?>"
                                                  class="btn btn-secondary btn-sm rotateImage"><i class="fa fa-undo"
                                                                                                  aria-hidden="true"></i></span>
                                        </div>
                                    </div>
                                </div>
                                <?php
                            }
                        }
                    } else {
                        ?>
                        <p>Nog geen afbeeldingen geupload</p>
                    <?php } ?>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<!-- Edit afbeelding -->
<?php echo $this->partial('blog/partial/edit_image.phtml'); ?>