<!-- YouTube video's -->
<div class="row" style="margin-bottom:15px;" id="youTubeVideosFrame">
    <?php foreach ($youTubeVideos AS $youTubeVideo) { ?>
        <div id="youTubeFrame<?php echo $youTubeVideo->getId() ?>" class="col-sm-12 col-md-4 col-lg-4" style="margin-bottom:10px;">
            <span data-youtubeid="<?php echo $youTubeVideo->getId() ?>" class="glyphicon glyphicon-remove removeYouTubeVideo" aria-hidden="true"></span>
            <?php $youTubeImage = $youTubeVideo->getYouTubeImageByType('maxres'); ?>
            <?php $imageURL = (is_object($youTubeVideo->getYouTubeImageByType('maxres')) ? $youTubeVideo->getYouTubeImageByType('maxres')->getUrl() : '/img/noimagefound.jpg'); ?>
            <?php if (!empty($imageURL)) { ?>
                <img class="img-responsive" src="<?php echo $imageURL; ?>" alt="<?php echo $youTubeVideo->getTitle(); ?>" />
            <?php } ?>
            <?php echo substr($youTubeVideo->getTitle(), 0, 25); ?>&hellip;
        </div>
    <?php } ?>
</div>
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <div class="form-group has-feedback">
            <div class="input-group">
                <span class="input-group-addon"><span class="glyphicon glyphicon-link" aria-hidden="true"></span></span>
                <input type="text" class="form-control" name="youtubevideolink">
            </div>
        </div>
    </div>
</div>
<button id="saveYouTubeVideo" type="button" class="btn btn-default">Add</button>