<div class="item">
    <h5 class="card-header">Categories</h5>
    <hr>
    <div class="card-body">
        <div class="row">
            <div class="col-lg-12">
                <?php
                foreach ($categories as $category) { ?>
                    <a href="<?php echo $this->url('blog', ['action' => 'category', 'id' => $category->getId()]); ?>"><?php echo $category->getName(); ?></a>
                    <br/>
                    <?php
                }
                ?>
                </ul>
            </div>
        </div>
    </div>
</div>