<div class="item">
    <h5 class="card-header mb-3">Search</h5>
    <hr/>
    <div class="card-body">
        <form action="<?php echo $this->url('blog', ['action' => 'search']); ?>" method="post" class="form-horizontal">
            <div class="input-group">
                <input type="text" name="searchString" value="<?php echo $searchTerm; ?>" class="form-control" placeholder="Search for..." />
                <div class="input-group-btn">
                    <button class="btn btn-primary btn-cyborg form-control" type="submit">Go!</button>
                </div>
            </div>
        </form>
    </div>
</div>