<div class="card my-4">
    <h5 class="card-header">Search</h5>
    <div class="card-body">
        <form action="<?php echo $this->url('blog', ['action' => 'search']); ?>" method="post" class="form-horizontal">
            <div class="input-group">
                <input type="text" name="searchString" value="<?php echo $searchTerm; ?>" class="form-control" placeholder="Search for..." />
                <span class="input-group-btn">
                    <button class="btn btn-secondary" type="submit">Go!</button>
                </span>
            </div>

        </form>
    </div>
</div>