
<!-- Page Header -->
<div class="row">
    <h1 class="col">ADD CATEGORIE</h1>
</div>
<!-- Breadcrumbs -->
<div class="row">
    <div class="col">
        <?= $this->pageBreadcrumbs()->render(); ?>
    </div>
</div>
<div class="row">
    <div class="col">
        <?php echo $this->form()->openTag($form); ?>
        <div class="form-group">
            <?php echo $this->formLabel($form->get('name')); ?>
            <div class="col-sm-6 col-md-6 col-lg-6">
                <?php echo $this->formText($form->get('name')); ?>
            </div>
            <div class="col-sm-5 col-md-5 col-lg-5">
                <?php echo(count($form->getMessages('name')) > 0 ? $form->getMessages('name')['isEmpty'] : '&nbsp;') ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel($form->get('description')); ?>
            <div class="col-sm-6 col-md-6 col-lg-6">
                <?php echo $this->formTextarea($form->get('description')); ?>
            </div>
            <div class="col-sm-5 col-md-5 col-lg-5">
                <?php echo(count($form->getMessages('description')) > 0 ? $form->getMessages('description')['isEmpty'] : '&nbsp;') ?>
            </div>
        </div>
        <div class="form-group row">
            <div class="col">
                <button type="submit" id="submit" class="btn btn-dark">Opslaan</button>
            </div>
            <div class="col text-right">
                <a href="<?php echo $this->url('beheer/categories'); ?>" class="btn btn-dark" title="Annuleren">Annuleren</a>
            </div>
        </div>
        <?php echo $this->form()->closeTag($form); ?>
    </div>
</div>
