<?php
$this->headTitle('Add Blog');

$this->mainMenu()->setActiveItemId('category');

$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'Categories' => $this->url('beheer/categories'),
    'Edit Category' => $this->url('beheer/categories', ['action' => 'edit'])
]);


$form->setAttributes(array(
    'class' => 'form-horizontal',
    'enctype' => 'multipart/form-data'
));
?>
<hgroup id="headAdminTitle" class="col-sm-12 col-md-12 col-lg-12">
    <h1 id="index">EDIT CATEGORY</h1>
</hgroup>
<div class="col-lg-12 col-md-12 col-sm-12">
    <!-- Breadcrumbs -->
    <?= $this->pageBreadcrumbs()->render(); ?>
</div>
<div class="col-lg-12 col-md-12 col-sm-12">
    <?php echo $this->form()->openTag($form); ?>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('name')); ?>
        <div class="col-sm-6 col-md-6 col-lg-6">
            <?php echo $this->formText($form->get('name')); ?>
        </div>
        <div class="col-sm-5 col-md-5 col-lg-5">
            <?php echo (count($form->getMessages('name')) > 0 ? $form->getMessages('name')['isEmpty'] : '&nbsp;' ) ?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('description')); ?>
        <div class="col-sm-6 col-md-6 col-lg-6">
            <?php echo $this->formTextarea($form->get('description')); ?>
        </div>
        <div class="col-sm-5 col-md-5 col-lg-5">
            <?php echo (count($form->getMessages('description')) > 0 ? $form->getMessages('description')['isEmpty'] : '&nbsp;' ) ?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-12 col-md-12 col-lg-12">
            <button type="submit" id="submit" class="btn btn-info">Opslaan</button> <a href="<?php echo $this->url['categorybeheer']; ?>" class="btn btn-default" title="Annuleren">Annuleren</a>
        </div>
    </div>
    <?php echo $this->form()->closeTag($form); ?>
</div>   
