<?php
$this->mainMenu()->setActiveItemId('overviewcategory');
$this->pageBreadcrumbs()->setLayout('beheer');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'Categories' => $this->url('beheer/categories'),
]);
?>
<!-- Page Header -->
<div class="row">
    <h1 class="col">CATEGORIE BEHEER</h1>
</div>
<!-- Breadcrumbs -->
<div class="row">
    <div class="col">
        <?= $this->pageBreadcrumbs()->render(); ?>
    </div>
</div>
<!-- Page header options -->
<div class="row mb-3">
    <div class="col">
        <a class="btn btn-secondary" href="
       <?= $this->url('beheer/categories', ['action' => 'add']); ?>">
            <i class="fas fa-plus-square"></i> New Categorie
        </a>
    </div>
</div>
<div class="row">
    <div class="col">
        <table class="table table-dark table-sm table-bordered table-hover table-striped">
            <thead class="thead-dark">
            <tr>
                <th>Titel</th>
                <th class="text-center"><i class="fas fa-cogs"></i></th>
            </tr>
            </thead>
            <tbody>
            <?php if (count($categories) > 0) { ?>
                <?php foreach ($categories AS $category) { ?>
                    <tr>
                        <td><?php echo $category->getName(); ?></td>
                        <td class="text-center">
                            <a class="btn btn-sm btn-secondary" href="
                           <?= $this->url('beheer/categories', ['action' => 'edit', 'id' => $category->getId()]); ?>">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a class="btn btn-sm btn-danger" href="
                           <?= $this->url('beheer/categories', ['action' => 'delete', 'id' => $category->getId()]); ?>">
                                <i class="fas fa-trash-alt"></i>
                            </a>
                        </td>
                    </tr>
                <?php } ?>
            <?php } ?>
            </tbody>
        </table>
    </div>
</div>