<?php
$this->mainMenu()->setActiveItemId('overviewcategory');

$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'Categories' => $this->url('beheer/categories'),
]);
?>
<hgroup id="headAdminTitle" class="col-sm-12 col-md-12 col-lg-12">
    <h1 id="index">CATEGORIE BEHEER</h1>
</hgroup>
<div class="col-lg-12 col-md-12 col-sm-12">
    <!-- Breadcrumbs -->
    <?= $this->pageBreadcrumbs()->render(); ?>
</div>
<p class="col-lg-12 col-md-12 col-sm-12">
    <a class="btn btn-default" href="
       <?= $this->url('beheer/categories', ['action' => 'add']); ?>">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Category
    </a>
</p>
<div class="col-lg-12 col-md-12 col-sm-12">
    <table class="table table-striped table-hover table-bordered">
        <tr>
            <th>Titel</th>
            <th style="text-align: center;"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></th>
        </tr>
        <?php if (count($categories) > 0) { ?>
            <?php foreach ($categories AS $category) { ?>
                <tr>
                    <td><?php echo $category->getName(); ?></td>
                    <td style="text-align: center;">
                        <a class="btn btn-primary" href="
                           <?= $this->url('beheer/categories', ['action' => 'edit', 'id' => $category->getId()]); ?>">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit
                        </a>
                        &nbsp;
                        <a class="btn btn-primary" href="
                           <?= $this->url('beheer/categories', ['action' => 'delete', 'id' => $category->getId()]); ?>">
                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Delete
                        </a>
                        </a>
                    </td>
                </tr>
            <?php } ?>
        <?php } ?>
    </table>
</div>