<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded  p-4">
                <div class="row g-4">
                    <h2 class="col-sm-12 col-md-12 col-xl-12 mb-4">Categorie&euml;n</h2>
                </div>
                <div class="row g-4">
                    <div class="col-sm-6 col-md-6 col-xl-6">
                        <a class="btn btn-primary" href="<?= $this->url('beheer/categories', ['action' => 'add']); ?>">
                            <i class="fas fa-plus-square"></i> New categorie
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded  p-4">
                <table class="table table-bordered table-hover table-striped">
                    <thead class="thead-dark">
                    <tr>
                        <th>Titel</th>
                        <th class="text-center"><i class="fas fa-cogs"></i></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if (count($categories) > 0) { ?>
                        <?php foreach ($categories as $category) { ?>
                            <tr>
                                <td><?php echo $category->getName(); ?></td>
                                <td class="text-center">
                                    <a class="btn btn-sm btn-secondary" href="
                           <?= $this->url('beheer/categories', ['action' => 'edit', 'id' => $category->getId()]); ?>">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <a class="btn btn-sm btn-danger" href="
                                        <?= $this->url('beheer/categories', ['action' => 'delete', 'id' => $category->getId()]); ?>">
                                        <i class="fas fa-trash-alt"></i>
                                    </a>
                                </td>
                            </tr>
                        <?php } ?>
                    <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="row g-4">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded mt-4 p-4">
                <?= $this->paginationControl($categories,
                    'Sliding',
                    'layout/paginator',
                    array('route' => 'beheer/categories')); ?>
            </div>
        </div>
    </div>
</div>
