<div class="most-popular module-page">
    <div class="row">
        <div class="col-lg-12">
            <div class="heading-section">
                <h4><em>Blogs</em> Right Now</h4>
            </div>
        </div>
        <div class="col-lg-8">
            <div class="row">
                <?php foreach ($blogs as $blog) { ?>
                    <?php
                    $images = $blog->getBlogImages();
                    foreach ($images as $image) {
                        foreach ($image->getImageTypes('400x200') as $imageType) {
                            $blogImage = '<img src="/' . $imageType->getFolder() . $imageType->getFileName() . '" alt="' . $image->getAlt() . '">';
                            break;
                        }
                        break;
                    }
                    ?>
                    <div class="col-lg-12 col-sm-12">
                        <div class="item">
                            <a href="<?php echo $this->url('blog', ['action' => 'detail', 'id' => $blog->getId()]); ?>">
                                <?= $blogImage ?>
                            </a>
                            <h4><?= $blog->getTitle(); ?>
                                <br><span><?= !empty($blog->getCategories()->first()) ? $blog->getCategories()->first()->getName() : ''; ?></span>
                            </h4>
                            <ul>
                                <li>Posted
                                    on <?php echo(is_object($blog->getDateCreated()) ? $blog->getDateCreated()->format('d F Y') : ''); ?>
                                    by
                                </li>
                                <li>
                                    <a href="#"><?php echo(is_object($blog->getCreatedBy()) ? $blog->getCreatedBy()->getFullName() : 'Onbekend'); ?></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                <?php } ?>
            </div>
            <!-- Pagination -->
            <?php
            echo $this->paginationControl($blogs, 'Sliding', 'partial/paginator');
            ?>
        </div>
        <div class="col-lg-4">
            <div class="fixed">
                <!-- Search Widget -->
                <?php echo $this->partial('partial/search_form.phtml'); ?>
                <!-- Categories Widget -->
                <?php echo $this->partial('partial/category_links.phtml', array('categories' => $categories)); ?>
            </div>
        </div>
    </div>
</div>