<div class="container-fluid pt-4 px-4">
    <?php $form->prepare(); ?>
    <?= $this->form()->openTag($form); ?>
    <?= $this->formRow($form->get('csrf')); ?>
    <div class="row g-4">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded p-4">
                <h2 class="mb-4">Add blog</h2>
                <div class="col-sm-12 col-md-12 col-xl-12">
                    <button type="button" class="btn btn-primary" id="buttonCategoryModal">
                        <i class="far fa-list-alt"></i>
                    </button>
                </div>
                <!-- Blog form -->
                <?= $this->partial('blog/partial/form.phtml', array('form' => $form)); ?>
                <!-- End blog form -->
            </div>
        </div>
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded p-4">
                <!-- Image upload -->
                <?= $this->partial('upload-images/partial/upload_image.phtml', array('form' => $form)); ?>
                <!-- End image upload -->
            </div>
        </div>
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded p-4">
                <div class="row">
                    <div class="col-sm-12 col-md-6 col-xl-6">
                        <?= $this->formRow($form->get('submit')); ?>
                    </div>
                    <div class="col-sm-12 col-md-6 col-xl-6 text-end">
                        <a href="<?= $this->url['blogbeheer']; ?>" class="btn btn-primary"
                           title="Annuleren">Annuleren</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- >Categories modal -->
    <?= $this->partial('blog/partial/categories.phtml', array('form' => $form)); ?>
    <!-- End Categories modal -->
    <?= $this->form()->closeTag($form); ?>
</div>

