<?php
$this->mainMenu()->setActiveItemId('archive');
$this->pageBreadcrumbs()->setLayout('beheer');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'Blog archief' => $this->url('beheer/blog', ['action' => 'archive']),
]);
?>
<!-- Page Header -->
<div class="row">
    <h1 class="col">BLOG ARCHIEF</h1>
</div>
<!-- Breadcrumbs -->
<div class="row">
    <div class="col">
        <?= $this->pageBreadcrumbs()->render(); ?>
    </div>
</div>
<div class="row">
    <div class="col">
        <table class="table table-dark table-sm table-bordered table-hover table-striped">
            <thead class="thead-dark">
            <tr>
                <th>Titel</th>
                <th>Datum aangemaakt</th>
                <th>Datum verwijderd</th>
                <th class="text-center"><i class="fas fa-cogs"></i></th>
            </tr>
            </thead>
            <tbody>
            <?php if (count($blogs) > 0) { ?>
                <?php foreach ($blogs AS $blog) { ?>
                    <tr>
                        <td><?php echo $blog->getTitle(); ?></td>
                        <td>
                            <?php echo(is_object($blog->getDateCreated()) ? $blog->getDateCreated()->format('d-m-Y H:m:s') : ''); ?>
                        </td>
                        <td>
                            <?php echo(is_object($blog->getDateDeleted()) ? $blog->getDateDeleted()->format('d-m-Y H:m:s') : ''); ?>
                        </td>
                        <td class="text-center">
                            <a class="btn btn-sm btn-danger" href="
                           <?= $this->url('beheer/blog', ['action' => 'delete', 'id' => $blog->getId()]); ?>">
                                <i class="fas fa-trash-alt"></i>
                            </a>

                            <a class="btn btn-sm btn-secondary" href="
                           <?= $this->url('beheer/blog', ['action' => 'un-archief', 'id' => $blog->getId()]); ?>">
                                <i class="fas fa-undo"></i>
                            </a>
                        </td>
                    </tr>
                <?php } ?>
            <?php } else { ?>
                <tr>
                    <td colspan="4" class="td-center">Niks gearchiveerd.</td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
</div>