<?php
$this->mainMenu()->setActiveItemId('archive');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'Blog archief' => $this->url('beheer/blog', ['action' => 'archive']),
]);
?>
<hgroup id="headAdminTitle" class="col-sm-12 col-md-12 col-lg-12">
    <h1 id="index">BLOG ARCHIEF</h1>
</hgroup>
<!-- Breadcrumbs -->
<div class="col-lg-12 col-md-12 col-sm-12">
    <?= $this->pageBreadcrumbs()->render(); ?>
</div>
<div class="col-lg-12 col-md-12 col-sm-12">
    <table class="table table-striped table-hover table-bordered">
        <tr>
            <th>Titel</th>
            <th>Datum aangemaakt</th>
            <th>Datum verwijderd</th>
            <th class="th-center"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span></th>
        </tr>
        <?php if (count($blogs) > 0) { ?>
            <?php foreach ($blogs AS $blog) { ?>
                <tr>
                    <td><?php echo $blog->getTitle(); ?></td>
                    <td>
                        <?php echo (is_object($blog->getDateCreated()) ? $blog->getDateCreated()->format('d-m-Y H:m:s') : ''); ?>
                    </td>
                    <td>
                        <?php echo (is_object($blog->getDateDeleted()) ? $blog->getDateDeleted()->format('d-m-Y H:m:s') : ''); ?>
                    </td>
                    <td class="td-center">
                        <a class="btn btn-primary" href="
                           <?= $this->url('beheer/blog', ['action' => 'delete', 'id' => $blog->getId()]); ?>">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Delete permanent
                        </a>
                        
                        <a class="btn btn-primary" href="
                           <?= $this->url('beheer/blog', ['action' => 'un-archief', 'id' => $blog->getId()]); ?>">
                            <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span> Zet blog terug
                        </a>
                    </td>
                </tr>
            <?php } ?>
        <?php } else { ?>
                <tr>
                    <td colspan="4" class="td-center">Niks gearchiveerd.</td>
                </tr>   
        <?php } ?>
    </table>
</div>