<?php
$this->headTitle('Add Blog');
$this->mainMenu()->setActiveItemId('blog');
$this->pageBreadcrumbs()->setLayout('beheer');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'Blogs' => $this->url('beheer/blog'),
    'Edit Blog' => $this->url('beheer/blog', ['action' => 'edit', 'id' => $blogId])
]);
$form->setAttributes(array(
    'class' => 'form-horizontal',
    'enctype' => 'multipart/form-data'
));
?>
!-- Page Header -->
<div class="row">
    <h1 class="col">ADD BLOG</h1>
</div>
<!-- Breadcrumbs -->
<div class="row">
    <div class="col">
        <?= $this->pageBreadcrumbs()->render(); ?>
    </div>
</div>
<?php echo $this->form()->openTag($form); ?>

<!-- Put blog id in hidden input field for use of js file -->
<input type="hidden" value="<?php echo $blogId; ?>" name="blogId"/>
<div class="row">
    <div class="col">
        <!-- Event form -->
        <?php
        echo $this->partial('blog/partial/form.phtml', array('form' => $form));
        ?>
        <!-- End event form -->
        <!-- Image upload -->
        <?php
        echo $this->partial('upload-images/partial/upload_image.phtml', array('formImage' => $formBlogImage));
        ?>
        <!-- End image upload -->
    </div>

</div>
<div class="row mb-2">
    <div class="col">
        <button type="submit" id="submit" class="btn btn-dark">Opslaan</button>
    </div>
    <div class="col text-right">
        <a href="<?php echo $this->url['blogbeheer']; ?>" class="btn btn-dark" title="Annuleren">Annuleren</a>
    </div>
</div>
<div class="row">
    <div class="col">
        <ul class="nav nav-pills" id="myTab" role="tablist">
            <li class="nav-item">
                <a class="nav-link  active" id="categories-tab" data-toggle="tab" href="#categories" role="tab"
                   aria-controls="categories" aria-selected="true">Categorie&euml;n</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="youtube-tab" data-toggle="tab" href="#youtube" role="tab"
                   aria-controls="youtube" aria-selected="false">You Tube</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="files-tab" data-toggle="tab" href="#files" role="tab" aria-controls="files"
                   aria-selected="false">Bestanden</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="images-tab" data-toggle="tab" href="#images" role="tab" aria-controls="images"
                   aria-selected="false">Afbeeldingen</a>
            </li>
        </ul>
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="categories" role="tabpanel" aria-labelledby="categories-tab">
                <!-- Categorieen -->
                <?php echo $this->partial('blog/partial/categories.phtml', array('form' => $form)); ?>
            </div>
            <div class="tab-pane fade" id="youtube" role="tabpanel" aria-labelledby="youtube-tab">
                <!-- YouTube video's -->
                <?php echo $this->partial('blog/partial/you_tube_videos.phtml', array('youTubeVideos' => $youTubeVideos)); ?>
            </div>
            <div class="tab-pane fade" id="files" role="tabpanel" aria-labelledby="files-tab">
                <!-- Bestanden -->
                <?php echo $this->partial('blog/partial/files.phtml'); ?>
            </div>
            <div class="tab-pane fade" id="images" role="tabpanel" aria-labelledby="images-tab">
                <!-- Afbeeldingen -->
                <?php echo $this->partial('blog/partial/show_images.phtml', array('images' => $images, 'returnURL' => $returnURL)); ?>
            </div>
        </div>
    </div>
    <?php echo $this->form()->closeTag($form); ?>
</div>