<?php
$this->mainMenu()->setActiveItemId('overviewblog');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'Blogs' => $this->url('beheer/blog'),
]);
?>
<hgroup id="headAdminTitle" class="col-sm-12 col-md-12 col-lg-12">
    <h1 id="index">BLOG BEHEER</h1>
</hgroup>
<!-- Breadcrumbs -->
<div class="col-lg-12 col-md-12 col-sm-12">
    <?= $this->pageBreadcrumbs()->render(); ?>
</div>
<p class="col-lg-12 col-md-12 col-sm-12">
    <a class="btn btn-default" href="
       <?= $this->url('beheer/blog', ['action' => 'add']); ?>">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Blog
    </a>
</p>
<div class="col-lg-12 col-md-12 col-sm-12">
    <table class="table table-striped table-hover table-bordered">
        <tr>
            <th>&nbsp;</th>
            <th>Titel</th>
            <th>Datum aangemaakt</th>
            <th>Datum gewijzigd</th>
            <th class="th-center"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span></th>
        </tr>
        <?php if (count($blogs) > 0) { ?>
            <?php foreach ($blogs AS $blog) { ?>
                <tr>
                    <td class="td-center"><span id="setOnlineOffline<?php echo $blog->getId(); ?>" data-blogid="<?php echo $blog->getId(); ?>" data-online="<?php echo ($blog->getOnline() == 1? 0:1); ?>" class="setOnlineOffline <?php echo ($blog->getOnline() == 0 ? 'blogOfflineActive' : 'blogOnlineActive'); ?> glyphicon glyphicon-eye-<?php echo ($blog->getOnline() == 0 ? 'close' : 'open'); ?>" aria-hidden="true"></span></td>
                    <td><?php echo $blog->getTitle(); ?></td>
                    <td>
                        <?php echo (is_object($blog->getDateCreated()) ? $blog->getDateCreated()->format('d-m-Y H:m:s') : ''); ?>
                    </td>
                    <td>
                        <?php echo (is_object($blog->getDateChanged()) ? $blog->getDateChanged()->format('d-m-Y H:m:s') : ''); ?>
                    </td>
                    <td class="td-center">
                        <a class="btn btn-primary" href="
                           <?= $this->url('beheer/blog', ['action' => 'edit', 'id' => $blog->getId()]); ?>">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit
                        </a>
                        &nbsp;
                        <a class="btn btn-primary" href="
                           <?= $this->url('beheer/blog', ['action' => 'archief', 'id' => $blog->getId()]); ?>">
                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Archiveer
                        </a>
                    </td>
                </tr>
            <?php } ?>
        <?php } ?>
    </table>
</div>

<script>
    $("span.setOnlineOffline").on("click", function () {
        var blogId = $(this).data('blogid');
        var online = $(this).data('online');

        if (blogId !== '' && online !== '') {

            $.ajax({
                type: 'POST',
                data: {
                    blogId: blogId,
                    online: online
                },
                url: "<?= $this->url('blogajaxbeheer', ['action' => 'setOnline']); ?>",
                async: true,
                success: function (data) {
                    if (data.succes === true) {
                       if (data.online == 1) {
                           $("span#setOnlineOffline" + data.blogId).removeClass('blogOfflineActive');
                           $("span#setOnlineOffline" + data.blogId).addClass('blogOnlineActive');
                           $("span#setOnlineOffline" + data.blogId).removeClass('glyphicon-eye-close');
                           $("span#setOnlineOffline" + data.blogId).addClass('glyphicon-eye-open');
                           $("span#setOnlineOffline" + data.blogId).data('online',0);
                       } else {
                           $("span#setOnlineOffline" + data.blogId).addClass('blogOfflineActive');
                           $("span#setOnlineOffline" + data.blogId).removeClass('blogOnlineActive');
                           $("span#setOnlineOffline" + data.blogId).addClass('glyphicon-eye-close');
                           $("span#setOnlineOffline" + data.blogId).removeClass('glyphicon-eye-open');
                           $("span#setOnlineOffline" + data.blogId).data('online',1);
                       }
                    } else {
                        alert(data.errorMessage);
                    }
                }
            });
        } else {
            alert('Er ging iets mis.');
        }

    });
</script>